### PR TITLE
Create Review file

### PR DESCRIPTION
**Pull request by Rajkumar0828**
Hi Vasan please review my code

### CODE REVIEW

**Comment by Princesince2001** [comment]
Great work Raj, your code seems to be good, I suggest it 
is good to remove the comment which are not necessary 
this promotes code standard and readability.

**Comment by Rajkumar0828** [comment]
Sure vasan, I make the changes which you have mentioned

**Comment by Rajkumar0828** [comment]
The changes are done vasan, The issues are resolved

**Comment by Princesince2001** [comment]
Okay Raj, the code is verified and resolved you can proceed with other formalities.

**Pull request merged**
